theme: jekyll-theme-cayman
title: Synthetic data generation for YOLO with Blender and Python
description: An extensive guide to generating training, labelled data for a real-life YOLO application      
